services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: postgres
    volumes:
        - ./db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=db
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

